---
cloud_snitch_repo_dir: /opt/cloud_snitch
cloud_snitch_playbook: "{{ cloud_snitch_repo_dir }}/collection/snitch.yml"

cloud_snitch_conf_dir: /etc/cloud_snitch
cloud_snitch_data_dir: "{{ cloud_snitch_conf_dir }}/data"
cloud_snitch_conf_file: "{{ cloud_snitch_conf_dir }}/cloud_snitch.yml"

cloud_snitch_inventory_locations:
  # - /opt/openstack-ansible/playbooks/inventory/
  - /opt/rpc-openstack/openstack-ansible/playbooks/inventory/

cloud_snitch_collection_timeout: 1800
cloud_snitch_collection_poll: 30
